blog/urls.py
from django.urls import path
from .views import(
	PostListView, 
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
    UserPostListView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view() , name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view() , name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
    path('contact/', views.contact, name='blog-contact'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from courses import views as course_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
    path('courses/', include('courses.urls', namespace='courses')), 
    path('memberships/', include('users.urls', namespace ='memberships'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import (
	MembershipSelectView, 
	PaymentView, 
	updateTransactionRecords,
	profile_view,
	cancelSubscription
	)

app_name = 'users'

urlpatterns = [
	path('', MembershipSelectView.as_view(), name='select'),
	path('payment/', PaymentView, name='payment'),
	path('update-transactions/<subscription_id>/', updateTransactionRecords, name='update-transactions'),
	path('profiles/', profile_view, name='profiles'),
    path('cancel/', cancelSubscription, name='cancel')
]

courses/models.py
from django.db import models
from django.urls import reverse

from users.models import Membership

class Course(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=120)
	description = models.TextField()
	allowed_memberships = models.ManyToManyField(Membership)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:detail', kwargs={'slug': self.slug})

	@property
	def lessons(self):
		return self.lesson_set.all().order_by('position')
	

class Lesson(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=120)
	course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
	position = models.IntegerField()
	video_url = models.CharField(max_length=200)
	thumbnail = models.ImageField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:lesson-detail',
			kwargs= {
				'course_slug': self.course.slug,
				'lesson_slug': self.slug
			})

users/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from PIL import Image

from datetime import datetime
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES = (
	('Enterprise', 'ent'),
	('Professional', 'pro'),
	('Free', 'free')
)

class Membership(models.Model):
	slug = models.SlugField()
	membership_type = models.CharField(
			choices=MEMBERSHIP_CHOICES,
			default='Free',
			max_length=30)
	price = models.IntegerField(default=15)
	stripe_plan_id = models.CharField(max_length=40)

	def __str__(self):
		return self.membership_type


class UserMembership(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	stripe_customer_id = models.CharField(max_length=40)
	membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.user.username

def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
	if created:
		UserMembership.objects.get_or_create(user=instance)

	user_membership, created = UserMembership.objects.get_or_create(user=instance)

	if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
		new_customer_id = stripe.Customer.create(email=instance.email)
		user_membership.stripe_customer_id = new_customer_id['id']
		user_membership.save()

post_save.connect(post_save_usermembership_create, sender=settings.AUTH_USER_MODEL)


class Subscription(models.Model):
	user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
	stripe_subscription_id = models.CharField(max_length=40)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.user_membership.user.username

	@property
	def get_created_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.created)

	@property
	def get_next_billing_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.current_period_end)


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['image']

users/views.py
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Membership, UserMembership, Subscription

import stripe

stripe.Token.create(
  card={
    "number": '4242424242424242',
    "exp_month": 12,
    "exp_year": 2019,
    "cvc": '123'
  },
)

def profile_view(request):
	user_membership = get_user_membership(request)
	user_subscription = get_user_subscription(request)
	context = {
		'user_membership': user_membership,
		'user_subscription': user_subscription
	}
	return render(request, "users/profile.html", context)

def get_user_membership(request):
	user_membership_qs = UserMembership.objects.filter(user=request.user)
	if user_membership_qs.exists():
		return user_membership_qs.first()
	return None

def get_user_subscription(request):
	user_subscription_qs = Subscription.objects.filter(
			user_membership=get_user_membership(request))
	if user_subscription_qs.exists():
		user_subscription = user_subscription_qs.first()
		return user_subscription
	return None

def get_selected_membership(request):
	membership_type = request.session['selected_membership_type']
	selected_membership_qs = Membership.objects.filter(
				membership_type=membership_type)
	if selected_membership_qs.exists():
		return selected_membership_qs.first()
	return None


class MembershipSelectView(ListView):
	model = Membership

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(**kwargs)
		current_membership = get_user_membership(self.request)
		context['current_membership'] = str(current_membership.membership)
		return context

	def post(self, request, **kwargs):
		user_membership = get_user_membership(request)
		user_subscription = get_user_subscription(request)

		selected_membership_type = request.POST.get('membership_type')

		selected_membership_qs = Membership.objects.filter(
				membership_type=selected_membership_type)
		print(selected_membership_qs)
		selected_membership = selected_membership_qs.first()
		print(selected_membership)
		'''
		==========
		VALIDATION
		==========
		'''

		if user_membership.membership == selected_membership:
			if user_subscription != None:
				messages.info(request, "You already have this membership. Your \
					next payment is due {}".format('get this value from stripe'))
				return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		# assign to the session
		request.session['selected_membership_type'] = selected_membership.membership_type

		return HttpResponseRedirect(reverse('memberships:payment'))



def PaymentView(request):

	user_membership = get_user_membership(request)

	selected_membership = get_selected_membership(request)

	publishKey = settings.STRIPE_PUBLISHABLE_KEY

	if request.method == "POST":
		try:
			token = request.POST['stripeToken']
			subscription = stripe.Subscription.create(
			  customer=user_membership.stripe_customer_id,
			  items=[
			    {
			      "plan": selected_membership.stripe_plan_id,
			    },
			  ],
			  source=stripe.Token # 4242424242424242
			)

			return redirect(reverse('memberships:update-transactions',
				kwargs={
					'subscription_id': subscription.id
				}))

		except stripe.card_error as e:
			messages.info(request, "Your card has been declined")

	context = {
		'publishKey': publishKey,
		'selected_membership': selected_membership
	}

	return render(request, "users/membership_payment.html", context)


def updateTransactionRecords(request, subscription_id):
	user_membership = get_user_membership(request)
	selected_membership = get_selected_membership(request)

	user_membership.membership = selected_membership
	user_membership.save()

	sub, created = Subscription.objects.get_or_create(user_membership=user_membership)
	sub.stripe_subscription_id = subscription_id
	sub.active = True
	sub.save()

	try:
		del request.session['selected_membership_type']
	except:
		pass

	messages.info(request, 'Successfully created {} membership'.format(selected_membership))
	return redirect('/users')


def cancelSubscription(request):
	user_sub = get_user_subscription(request)

	if user_sub.active == False:
		messages.info(request, "You dont have an active membership")
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
	sub.delete()

	user_sub.active = False
	user_sub.save()


	free_membership = Membership.objects.filter(membership_type='Free').first()
	user_membership = get_user_membership(request)
	user_membership.membership = free_membership
	user_membership.save()

	messages.info(request, "Successfully cancelled membership. We have sent an email")
	# sending an email here

	return redirect('/users')

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account created for {username}!')
			return redirect('login')
	else:
		form = UserRegisterForm()

	return render (request,'users/register.html', {'form': form})

@login_required
def profile(request):
	return render(request, 'users/profile.html')

@login_required
def profile(request):
	if request.method =='POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f'Your account has been updated!')
			return redirect('profile')
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)

	context = {
		'u_form': u_form,
		'p_form': p_form
	}

	return render(request, 'users/profile.html', context)

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Welcome Back!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Do not have an Account? <a class="ml-2" href="#">Register</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
	<legend class="border-bottom mb-4">You have been Logged Out </legend>
        <small class="text-muted">
            <h5> Oops, made a mistake... <a href="{% url 'login' %}">Log In Again </a> </h5>
        </small>
    </div>
{% endblock content %}

users/templates/users/membership_list.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="content-section">
	 <legend class="border-bottom mb-3"> Select a membership </legend>
	<div class="row">
		{% for object in object_list %}
		<div class="col-sm-4 col-md-4">
			<h4>{{ object.membership_type }}</h4>
			<p> Price: IDR {{ object.price }} <small> /month </small> </p>
			<h4> Included Courses </h4>
			<ul>
				{% for course in object.course_set.all %}
					<li>{{ course.title }}</li>
				{% endfor %}
			</ul>
			{% if object.membership_type != 'Free' %}
			<form method="POST" action="{% url 'users:select' %}">
				{% csrf_token %}
				{% if object.membership_type != current_membership %}
					<center> <button class="btn btn-warning mt-2 mb-2">Select</button> </center>
				{% else %}
					<small>This is your current membership</small>
				{% endif %}
				<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
			</form>			
			{% endif %}	
		</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <legend class="account-heading border-bottom mb-4"> {{ user.username }} </legend>
          <ul class="mb-3" >
          <li class="text-secondary"> E-mail: {{ user.email }}</li>
          </ul>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group mt-4 ">
                <legend class="border-bottom mb-4">Edit Profile Information</legend>
                {{u_form|crispy }}
                {{p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/profiles.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
	<div class="row">
		<h1>My Profile</h1>
		<div class="col-sm-4 col-md-4">
			{% if user_subscription != None %}
				<h4>Current Membership: {{ user_membership.membership.membership_type }} <small>since {{ user_subscription.get_created_date }}</small></h4>

				{% if user_subscription.active != False %}
					<p>Next payment due: {{ user_subscription.get_next_billing_date }}</p>
					<a href="{% url 'memberships:cancel' %}">Cancel subscription</a>

				{% else %}
					<p>You don't have an active membership plan. Check them out here 
						<a href="{% url 'memberships:select' %}"></a>
					</p>
				{% endif %}
			{% endif %}
		</div>
	</div>
</div>	
{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Register</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an Account? <a class="ml-2" href="#">Log In</a>
            </small>
        </div>
    </div>
{% endblock content %}